project:
  type: website
  render:
    - "*.qmd"
website:
  title: "AIML4OS Funathon - Project 3"
  page-navigation: true
  description: "Satellite images segmentation"
  site-url: "https://aiml4os.github.io/funathon-project3/"
  repo-url: "https://github.com/AIML4OS/funathon-project3"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right:
    - text: "License"
      href: LICENCE

  navbar:
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: "https://github.com/AIML4OS/funathon-project3"
        aria-label: GitHub

    left:
      - text: "Introduction"
        href: index.qmd
      - text: "Training Dataset"
        href: 1-acquisition.qmd
      - text: "Model Explanation"
        href: 2-model.qmd
      - text: "Model Training"
        href: 3-training.qmd
      - text: "Inference"
        href: 4-inference.qmd
      - text: "Statistics"
        href: 5-statistics.qmd

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    reference-location: margin
    code-copy: true
    code-overflow: wrap

execute:
  eval: false
  warning: false
